/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chat {
  'muted' : Array<[string, boolean]>,
  'participants' : Array<UserId>,
  'vanishMode' : boolean,
  'createdAt' : Timestamp,
  'lastMessage' : [] | [MessageId],
  'lastUpdated' : Timestamp,
  'typing' : Array<[string, boolean]>,
  'pinned' : Array<[string, boolean]>,
  'archived' : Array<[string, boolean]>,
}
export interface GroupChat {
  'id' : string,
  'members' : Array<UserId>,
  'name' : string,
  'createdAt' : Timestamp,
  'lastMessage' : [] | [string],
  'lastUpdated' : Timestamp,
  'typing' : Array<[string, boolean]>,
  'description' : string,
  'adminId' : UserId,
}
export interface Message {
  'edited' : boolean,
  'createdAt' : Timestamp,
  'text' : string,
  'vanish' : boolean,
  'seenBy' : Array<UserId>,
  'mediaUrl' : string,
  'messageType' : MessageType,
  'deletedForEveryone' : boolean,
  'replyTo' : [] | [MessageId],
  'editedAt' : [] | [Timestamp],
  'reactions' : Array<[string, Array<UserId>]>,
  'senderId' : UserId,
}
export type MessageId = string;
export type MessageType = { 'gif' : null } |
  { 'video' : null } |
  { 'voice' : null } |
  { 'file' : null } |
  { 'text' : null } |
  { 'image' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  '_id' : UserId,
  'bio' : string,
  'blockedUsers' : Array<UserId>,
  'timezone' : string,
  'fcmToken' : string,
  'username' : string,
  'birthDate' : string,
  'websiteUrl' : string,
  'createdAt' : Timestamp,
  'fullName' : string,
  'email' : string,
  'isPrivate' : boolean,
  'onlineStatus' : boolean,
  'phoneNumber' : string,
  'followers' : Array<UserId>,
  'following' : Array<UserId>,
  'profilePicture' : string,
  'lastSeen' : Timestamp,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGroupMember' : ActorMethod<[string, Principal], undefined>,
  'addReaction' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'createGroupChat' : ActorMethod<[string, string, Array<Principal>], string>,
  'createOrUpdateUserProfile' : ActorMethod<[UserProfile], undefined>,
  'createTemporaryFolder' : ActorMethod<[string], undefined>,
  'deleteAccount' : ActorMethod<[], undefined>,
  'deleteMessageForEveryone' : ActorMethod<[string, string], undefined>,
  'deleteTemporaryFolder' : ActorMethod<[string], undefined>,
  'editMessage' : ActorMethod<[string, string, string], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatById' : ActorMethod<[string], [] | [Chat]>,
  'getChatMessages' : ActorMethod<[string, bigint], Array<Message>>,
  'getEmailByPhoneNumber' : ActorMethod<[string], string>,
  'getGroupById' : ActorMethod<[string], [] | [GroupChat]>,
  'getGroupMessages' : ActorMethod<[string, bigint], Array<Message>>,
  'getLifestyleChoices' : ActorMethod<[], Array<string>>,
  'getMyChats' : ActorMethod<[], Array<Chat>>,
  'getMyGroupChats' : ActorMethod<[], Array<GroupChat>>,
  'getOrCreateChat' : ActorMethod<[Principal], Chat>,
  'getPersonalityTypes' : ActorMethod<[], Array<string>>,
  'getRelationshipStatuses' : ActorMethod<[], Array<string>>,
  'getTemporaryFolders' : ActorMethod<[], Array<string>>,
  'getTypingStatus' : ActorMethod<[string], Array<[string, boolean]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWellBeingPractices' : ActorMethod<[], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'leaveGroup' : ActorMethod<[string], undefined>,
  'markGroupMessagesSeen' : ActorMethod<[string], undefined>,
  'markMessagesSeen' : ActorMethod<[string], undefined>,
  'removeGroupMember' : ActorMethod<[string, Principal], undefined>,
  'removeReaction' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchFolders' : ActorMethod<[string], Array<string>>,
  'searchProfiles' : ActorMethod<[string], Array<UserProfile>>,
  'searchUsersByUsername' : ActorMethod<[string], Array<UserProfile>>,
  'searchUsersByUsernamePrefix' : ActorMethod<[string], Array<UserProfile>>,
  'sendGroupMessage' : ActorMethod<
    [string, string, string, string, string],
    Message
  >,
  'sendMessage' : ActorMethod<
    [string, string, string, string, string],
    Message
  >,
  'setGroupTypingStatus' : ActorMethod<[string, boolean], undefined>,
  'setTypingStatus' : ActorMethod<[string, boolean], undefined>,
  'toggleArchive' : ActorMethod<[string], undefined>,
  'toggleMute' : ActorMethod<[string], undefined>,
  'togglePin' : ActorMethod<[string], undefined>,
  'toggleVanishMode' : ActorMethod<[string], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'updateGroupInfo' : ActorMethod<[string, string, string], undefined>,
  'updateLastSeen' : ActorMethod<[], undefined>,
  'updateOnlineStatus' : ActorMethod<[boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];