/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  '_id' : UserId,
  'bio' : IDL.Text,
  'blockedUsers' : IDL.Vec(UserId),
  'timezone' : IDL.Text,
  'fcmToken' : IDL.Text,
  'username' : IDL.Text,
  'birthDate' : IDL.Text,
  'websiteUrl' : IDL.Text,
  'createdAt' : Timestamp,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'isPrivate' : IDL.Bool,
  'onlineStatus' : IDL.Bool,
  'phoneNumber' : IDL.Text,
  'followers' : IDL.Vec(UserId),
  'following' : IDL.Vec(UserId),
  'profilePicture' : IDL.Text,
  'lastSeen' : Timestamp,
});
export const MessageId = IDL.Text;
export const Chat = IDL.Record({
  'muted' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'participants' : IDL.Vec(UserId),
  'vanishMode' : IDL.Bool,
  'createdAt' : Timestamp,
  'lastMessage' : IDL.Opt(MessageId),
  'lastUpdated' : Timestamp,
  'typing' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'pinned' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'archived' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
});
export const MessageType = IDL.Variant({
  'gif' : IDL.Null,
  'video' : IDL.Null,
  'voice' : IDL.Null,
  'file' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const Message = IDL.Record({
  'edited' : IDL.Bool,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'vanish' : IDL.Bool,
  'seenBy' : IDL.Vec(UserId),
  'mediaUrl' : IDL.Text,
  'messageType' : MessageType,
  'deletedForEveryone' : IDL.Bool,
  'replyTo' : IDL.Opt(MessageId),
  'editedAt' : IDL.Opt(Timestamp),
  'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(UserId))),
  'senderId' : UserId,
});
export const GroupChat = IDL.Record({
  'id' : IDL.Text,
  'members' : IDL.Vec(UserId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'lastMessage' : IDL.Opt(IDL.Text),
  'lastUpdated' : Timestamp,
  'typing' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'description' : IDL.Text,
  'adminId' : UserId,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGroupMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'addReaction' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createGroupChat' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Principal)],
      [IDL.Text],
      [],
    ),
  'createOrUpdateUserProfile' : IDL.Func([UserProfile], [], []),
  'createTemporaryFolder' : IDL.Func([IDL.Text], [], []),
  'deleteAccount' : IDL.Func([], [], []),
  'deleteMessageForEveryone' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteTemporaryFolder' : IDL.Func([IDL.Text], [], []),
  'editMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatById' : IDL.Func([IDL.Text], [IDL.Opt(Chat)], ['query']),
  'getChatMessages' : IDL.Func(
      [IDL.Text, IDL.Int],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getEmailByPhoneNumber' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getGroupById' : IDL.Func([IDL.Text], [IDL.Opt(GroupChat)], ['query']),
  'getGroupMessages' : IDL.Func(
      [IDL.Text, IDL.Int],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getLifestyleChoices' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMyChats' : IDL.Func([], [IDL.Vec(Chat)], ['query']),
  'getMyGroupChats' : IDL.Func([], [IDL.Vec(GroupChat)], ['query']),
  'getOrCreateChat' : IDL.Func([IDL.Principal], [Chat], []),
  'getPersonalityTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRelationshipStatuses' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTemporaryFolders' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTypingStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWellBeingPractices' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveGroup' : IDL.Func([IDL.Text], [], []),
  'markGroupMessagesSeen' : IDL.Func([IDL.Text], [], []),
  'markMessagesSeen' : IDL.Func([IDL.Text], [], []),
  'removeGroupMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'removeReaction' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchFolders' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'searchProfiles' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], []),
  'searchUsersByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'searchUsersByUsernamePrefix' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'sendGroupMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Message],
      [],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Message],
      [],
    ),
  'setGroupTypingStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setTypingStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'toggleArchive' : IDL.Func([IDL.Text], [], []),
  'toggleMute' : IDL.Func([IDL.Text], [], []),
  'togglePin' : IDL.Func([IDL.Text], [], []),
  'toggleVanishMode' : IDL.Func([IDL.Text], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'updateGroupInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateLastSeen' : IDL.Func([], [], []),
  'updateOnlineStatus' : IDL.Func([IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    '_id' : UserId,
    'bio' : IDL.Text,
    'blockedUsers' : IDL.Vec(UserId),
    'timezone' : IDL.Text,
    'fcmToken' : IDL.Text,
    'username' : IDL.Text,
    'birthDate' : IDL.Text,
    'websiteUrl' : IDL.Text,
    'createdAt' : Timestamp,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'isPrivate' : IDL.Bool,
    'onlineStatus' : IDL.Bool,
    'phoneNumber' : IDL.Text,
    'followers' : IDL.Vec(UserId),
    'following' : IDL.Vec(UserId),
    'profilePicture' : IDL.Text,
    'lastSeen' : Timestamp,
  });
  const MessageId = IDL.Text;
  const Chat = IDL.Record({
    'muted' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'participants' : IDL.Vec(UserId),
    'vanishMode' : IDL.Bool,
    'createdAt' : Timestamp,
    'lastMessage' : IDL.Opt(MessageId),
    'lastUpdated' : Timestamp,
    'typing' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'pinned' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'archived' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  });
  const MessageType = IDL.Variant({
    'gif' : IDL.Null,
    'video' : IDL.Null,
    'voice' : IDL.Null,
    'file' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const Message = IDL.Record({
    'edited' : IDL.Bool,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'vanish' : IDL.Bool,
    'seenBy' : IDL.Vec(UserId),
    'mediaUrl' : IDL.Text,
    'messageType' : MessageType,
    'deletedForEveryone' : IDL.Bool,
    'replyTo' : IDL.Opt(MessageId),
    'editedAt' : IDL.Opt(Timestamp),
    'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(UserId))),
    'senderId' : UserId,
  });
  const GroupChat = IDL.Record({
    'id' : IDL.Text,
    'members' : IDL.Vec(UserId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'lastMessage' : IDL.Opt(IDL.Text),
    'lastUpdated' : Timestamp,
    'typing' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'description' : IDL.Text,
    'adminId' : UserId,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGroupMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'addReaction' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createGroupChat' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Principal)],
        [IDL.Text],
        [],
      ),
    'createOrUpdateUserProfile' : IDL.Func([UserProfile], [], []),
    'createTemporaryFolder' : IDL.Func([IDL.Text], [], []),
    'deleteAccount' : IDL.Func([], [], []),
    'deleteMessageForEveryone' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteTemporaryFolder' : IDL.Func([IDL.Text], [], []),
    'editMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatById' : IDL.Func([IDL.Text], [IDL.Opt(Chat)], ['query']),
    'getChatMessages' : IDL.Func(
        [IDL.Text, IDL.Int],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getEmailByPhoneNumber' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getGroupById' : IDL.Func([IDL.Text], [IDL.Opt(GroupChat)], ['query']),
    'getGroupMessages' : IDL.Func(
        [IDL.Text, IDL.Int],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getLifestyleChoices' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMyChats' : IDL.Func([], [IDL.Vec(Chat)], ['query']),
    'getMyGroupChats' : IDL.Func([], [IDL.Vec(GroupChat)], ['query']),
    'getOrCreateChat' : IDL.Func([IDL.Principal], [Chat], []),
    'getPersonalityTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRelationshipStatuses' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTemporaryFolders' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTypingStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWellBeingPractices' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveGroup' : IDL.Func([IDL.Text], [], []),
    'markGroupMessagesSeen' : IDL.Func([IDL.Text], [], []),
    'markMessagesSeen' : IDL.Func([IDL.Text], [], []),
    'removeGroupMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'removeReaction' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchFolders' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'searchProfiles' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], []),
    'searchUsersByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'searchUsersByUsernamePrefix' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'sendGroupMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Message],
        [],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Message],
        [],
      ),
    'setGroupTypingStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setTypingStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'toggleArchive' : IDL.Func([IDL.Text], [], []),
    'toggleMute' : IDL.Func([IDL.Text], [], []),
    'togglePin' : IDL.Func([IDL.Text], [], []),
    'toggleVanishMode' : IDL.Func([IDL.Text], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'updateGroupInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateLastSeen' : IDL.Func([], [], []),
    'updateOnlineStatus' : IDL.Func([IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };