/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const UserProfile = IDL.Record({
  '_id' : UserId,
  'bio' : IDL.Text,
  'blockedUsers' : IDL.Vec(UserId),
  'timezone' : IDL.Text,
  'fcmToken' : IDL.Text,
  'username' : IDL.Text,
  'closeFriends' : IDL.Vec(UserId),
  'birthDate' : IDL.Text,
  'websiteUrl' : IDL.Text,
  'createdAt' : Timestamp,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'isPrivate' : IDL.Bool,
  'onlineStatus' : IDL.Bool,
  'phoneNumber' : IDL.Text,
  'followers' : IDL.Vec(UserId),
  'following' : IDL.Vec(UserId),
  'profilePicture' : IDL.Text,
  'lastSeen' : Timestamp,
});
export const StatusId = IDL.Text;
export const Status = IDL.Record({
  'id' : StatusId,
  'expiresAt' : Timestamp,
  'views' : IDL.Vec(UserId),
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'photoUrl' : IDL.Text,
  'privacy' : IDL.Text,
  'bgColor' : IDL.Text,
});
export const StoryId = IDL.Text;
export const Story = IDL.Record({
  'id' : StoryId,
  'highlightTitle' : IDL.Text,
  'expiresAt' : Timestamp,
  'isCloseFriends' : IDL.Bool,
  'views' : IDL.Vec(UserId),
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'mediaUrl' : IDL.Text,
  'isHighlight' : IDL.Bool,
  'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(UserId))),
  'bgColor' : IDL.Text,
});
export const ChannelId = IDL.Text;
export const MessageId = IDL.Text;
export const Channel = IDL.Record({
  'id' : ChannelId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'subscribers' : IDL.Vec(UserId),
  'inviteLink' : IDL.Text,
  'isPublic' : IDL.Bool,
  'adminId' : UserId,
  'slowModeSecs' : IDL.Nat,
  'rules' : IDL.Text,
  'pinnedMessageId' : IDL.Opt(MessageId),
});
export const MessageType = IDL.Variant({
  'gif' : IDL.Null,
  'video' : IDL.Null,
  'voice' : IDL.Null,
  'file' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const Message = IDL.Record({
  'edited' : IDL.Bool,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'vanish' : IDL.Bool,
  'seenBy' : IDL.Vec(UserId),
  'mediaUrl' : IDL.Text,
  'messageType' : MessageType,
  'deletedForEveryone' : IDL.Bool,
  'replyTo' : IDL.Opt(MessageId),
  'editedAt' : IDL.Opt(Timestamp),
  'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(UserId))),
  'senderId' : UserId,
});
export const Chat = IDL.Record({
  'muted' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'participants' : IDL.Vec(UserId),
  'vanishMode' : IDL.Bool,
  'createdAt' : Timestamp,
  'lastMessage' : IDL.Opt(MessageId),
  'lastUpdated' : Timestamp,
  'typing' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'pinned' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'archived' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
});
export const GroupChat = IDL.Record({
  'id' : IDL.Text,
  'members' : IDL.Vec(UserId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'lastMessage' : IDL.Opt(IDL.Text),
  'lastUpdated' : Timestamp,
  'slowMode' : IDL.Nat,
  'typing' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'description' : IDL.Text,
  'inviteLink' : IDL.Text,
  'adminId' : UserId,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCloseFriend' : IDL.Func([IDL.Principal], [], []),
  'addGroupMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'addReaction' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addToHighlights' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createChannel' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Text],
      [],
    ),
  'createGroupChat' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Principal)],
      [IDL.Text],
      [],
    ),
  'createOrUpdateUserProfile' : IDL.Func([UserProfile], [], []),
  'createStatus' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Status],
      [],
    ),
  'createStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [Story],
      [],
    ),
  'createTemporaryFolder' : IDL.Func([IDL.Text], [], []),
  'deleteAccount' : IDL.Func([], [], []),
  'deleteMessageForEveryone' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteStatus' : IDL.Func([IDL.Text], [], []),
  'deleteStory' : IDL.Func([IDL.Text], [], []),
  'deleteTemporaryFolder' : IDL.Func([IDL.Text], [], []),
  'editMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'generateChannelInviteLink' : IDL.Func([IDL.Text], [IDL.Text], []),
  'generateGroupInviteLink' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelById' : IDL.Func([IDL.Text], [IDL.Opt(Channel)], ['query']),
  'getChannelMessages' : IDL.Func(
      [IDL.Text, IDL.Int],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'getChatById' : IDL.Func([IDL.Text], [IDL.Opt(Chat)], ['query']),
  'getChatMessages' : IDL.Func(
      [IDL.Text, IDL.Int],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getCloseFriends' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getEmailByPhoneNumber' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getGroupById' : IDL.Func([IDL.Text], [IDL.Opt(GroupChat)], ['query']),
  'getGroupMessages' : IDL.Func(
      [IDL.Text, IDL.Int],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getHighlights' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
  'getLifestyleChoices' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMyChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
  'getMyChats' : IDL.Func([], [IDL.Vec(Chat)], ['query']),
  'getMyGroupChats' : IDL.Func([], [IDL.Vec(GroupChat)], ['query']),
  'getMyStatuses' : IDL.Func([], [IDL.Vec(Status)], ['query']),
  'getMyStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getOrCreateChat' : IDL.Func([IDL.Principal], [Chat], []),
  'getPersonalityTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRelationshipStatuses' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getStatusFeed' : IDL.Func([], [IDL.Vec(Status)], ['query']),
  'getStoriesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
  'getStoriesForFeed' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Story)))],
      ['query'],
    ),
  'getTemporaryFolders' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTypingStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWellBeingPractices' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinChannel' : IDL.Func([IDL.Text], [], []),
  'joinChannelByInviteLink' : IDL.Func([IDL.Text], [], []),
  'joinGroupByInviteLink' : IDL.Func([IDL.Text], [], []),
  'leaveChannel' : IDL.Func([IDL.Text], [], []),
  'leaveGroup' : IDL.Func([IDL.Text], [], []),
  'markGroupMessagesSeen' : IDL.Func([IDL.Text], [], []),
  'markMessagesSeen' : IDL.Func([IDL.Text], [], []),
  'markStatusViewed' : IDL.Func([IDL.Text], [], []),
  'markStoryViewed' : IDL.Func([IDL.Text], [], []),
  'pinMessageInChannel' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'postToChannel' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Message],
      [],
    ),
  'reactToStory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeCloseFriend' : IDL.Func([IDL.Principal], [], []),
  'removeGroupMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'removeReaction' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchFolders' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'searchProfiles' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], []),
  'searchUsersByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'searchUsersByUsernamePrefix' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'sendGroupMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Message],
      [],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Message],
      [],
    ),
  'setGroupSlowMode' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'setGroupTypingStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setTypingStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'toggleArchive' : IDL.Func([IDL.Text], [], []),
  'toggleMute' : IDL.Func([IDL.Text], [], []),
  'togglePin' : IDL.Func([IDL.Text], [], []),
  'toggleVanishMode' : IDL.Func([IDL.Text], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'updateChannelInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateGroupInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateLastSeen' : IDL.Func([], [], []),
  'updateOnlineStatus' : IDL.Func([IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const UserProfile = IDL.Record({
    '_id' : UserId,
    'bio' : IDL.Text,
    'blockedUsers' : IDL.Vec(UserId),
    'timezone' : IDL.Text,
    'fcmToken' : IDL.Text,
    'username' : IDL.Text,
    'closeFriends' : IDL.Vec(UserId),
    'birthDate' : IDL.Text,
    'websiteUrl' : IDL.Text,
    'createdAt' : Timestamp,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'isPrivate' : IDL.Bool,
    'onlineStatus' : IDL.Bool,
    'phoneNumber' : IDL.Text,
    'followers' : IDL.Vec(UserId),
    'following' : IDL.Vec(UserId),
    'profilePicture' : IDL.Text,
    'lastSeen' : Timestamp,
  });
  const StatusId = IDL.Text;
  const Status = IDL.Record({
    'id' : StatusId,
    'expiresAt' : Timestamp,
    'views' : IDL.Vec(UserId),
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'photoUrl' : IDL.Text,
    'privacy' : IDL.Text,
    'bgColor' : IDL.Text,
  });
  const StoryId = IDL.Text;
  const Story = IDL.Record({
    'id' : StoryId,
    'highlightTitle' : IDL.Text,
    'expiresAt' : Timestamp,
    'isCloseFriends' : IDL.Bool,
    'views' : IDL.Vec(UserId),
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'mediaUrl' : IDL.Text,
    'isHighlight' : IDL.Bool,
    'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(UserId))),
    'bgColor' : IDL.Text,
  });
  const ChannelId = IDL.Text;
  const MessageId = IDL.Text;
  const Channel = IDL.Record({
    'id' : ChannelId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'subscribers' : IDL.Vec(UserId),
    'inviteLink' : IDL.Text,
    'isPublic' : IDL.Bool,
    'adminId' : UserId,
    'slowModeSecs' : IDL.Nat,
    'rules' : IDL.Text,
    'pinnedMessageId' : IDL.Opt(MessageId),
  });
  const MessageType = IDL.Variant({
    'gif' : IDL.Null,
    'video' : IDL.Null,
    'voice' : IDL.Null,
    'file' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const Message = IDL.Record({
    'edited' : IDL.Bool,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'vanish' : IDL.Bool,
    'seenBy' : IDL.Vec(UserId),
    'mediaUrl' : IDL.Text,
    'messageType' : MessageType,
    'deletedForEveryone' : IDL.Bool,
    'replyTo' : IDL.Opt(MessageId),
    'editedAt' : IDL.Opt(Timestamp),
    'reactions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(UserId))),
    'senderId' : UserId,
  });
  const Chat = IDL.Record({
    'muted' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'participants' : IDL.Vec(UserId),
    'vanishMode' : IDL.Bool,
    'createdAt' : Timestamp,
    'lastMessage' : IDL.Opt(MessageId),
    'lastUpdated' : Timestamp,
    'typing' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'pinned' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'archived' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  });
  const GroupChat = IDL.Record({
    'id' : IDL.Text,
    'members' : IDL.Vec(UserId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'lastMessage' : IDL.Opt(IDL.Text),
    'lastUpdated' : Timestamp,
    'slowMode' : IDL.Nat,
    'typing' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'description' : IDL.Text,
    'inviteLink' : IDL.Text,
    'adminId' : UserId,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCloseFriend' : IDL.Func([IDL.Principal], [], []),
    'addGroupMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'addReaction' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addToHighlights' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createChannel' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Text],
        [],
      ),
    'createGroupChat' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Principal)],
        [IDL.Text],
        [],
      ),
    'createOrUpdateUserProfile' : IDL.Func([UserProfile], [], []),
    'createStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Status],
        [],
      ),
    'createStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [Story],
        [],
      ),
    'createTemporaryFolder' : IDL.Func([IDL.Text], [], []),
    'deleteAccount' : IDL.Func([], [], []),
    'deleteMessageForEveryone' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteStatus' : IDL.Func([IDL.Text], [], []),
    'deleteStory' : IDL.Func([IDL.Text], [], []),
    'deleteTemporaryFolder' : IDL.Func([IDL.Text], [], []),
    'editMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'generateChannelInviteLink' : IDL.Func([IDL.Text], [IDL.Text], []),
    'generateGroupInviteLink' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelById' : IDL.Func([IDL.Text], [IDL.Opt(Channel)], ['query']),
    'getChannelMessages' : IDL.Func(
        [IDL.Text, IDL.Int],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'getChatById' : IDL.Func([IDL.Text], [IDL.Opt(Chat)], ['query']),
    'getChatMessages' : IDL.Func(
        [IDL.Text, IDL.Int],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getCloseFriends' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getEmailByPhoneNumber' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getGroupById' : IDL.Func([IDL.Text], [IDL.Opt(GroupChat)], ['query']),
    'getGroupMessages' : IDL.Func(
        [IDL.Text, IDL.Int],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getHighlights' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
    'getLifestyleChoices' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMyChannels' : IDL.Func([], [IDL.Vec(Channel)], ['query']),
    'getMyChats' : IDL.Func([], [IDL.Vec(Chat)], ['query']),
    'getMyGroupChats' : IDL.Func([], [IDL.Vec(GroupChat)], ['query']),
    'getMyStatuses' : IDL.Func([], [IDL.Vec(Status)], ['query']),
    'getMyStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getOrCreateChat' : IDL.Func([IDL.Principal], [Chat], []),
    'getPersonalityTypes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRelationshipStatuses' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getStatusFeed' : IDL.Func([], [IDL.Vec(Status)], ['query']),
    'getStoriesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
    'getStoriesForFeed' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Story)))],
        ['query'],
      ),
    'getTemporaryFolders' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTypingStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWellBeingPractices' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinChannel' : IDL.Func([IDL.Text], [], []),
    'joinChannelByInviteLink' : IDL.Func([IDL.Text], [], []),
    'joinGroupByInviteLink' : IDL.Func([IDL.Text], [], []),
    'leaveChannel' : IDL.Func([IDL.Text], [], []),
    'leaveGroup' : IDL.Func([IDL.Text], [], []),
    'markGroupMessagesSeen' : IDL.Func([IDL.Text], [], []),
    'markMessagesSeen' : IDL.Func([IDL.Text], [], []),
    'markStatusViewed' : IDL.Func([IDL.Text], [], []),
    'markStoryViewed' : IDL.Func([IDL.Text], [], []),
    'pinMessageInChannel' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'postToChannel' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Message],
        [],
      ),
    'reactToStory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeCloseFriend' : IDL.Func([IDL.Principal], [], []),
    'removeGroupMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'removeReaction' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchFolders' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'searchProfiles' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], []),
    'searchUsersByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'searchUsersByUsernamePrefix' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'sendGroupMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Message],
        [],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Message],
        [],
      ),
    'setGroupSlowMode' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'setGroupTypingStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setTypingStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'toggleArchive' : IDL.Func([IDL.Text], [], []),
    'toggleMute' : IDL.Func([IDL.Text], [], []),
    'togglePin' : IDL.Func([IDL.Text], [], []),
    'toggleVanishMode' : IDL.Func([IDL.Text], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'updateChannelInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateGroupInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateLastSeen' : IDL.Func([], [], []),
    'updateOnlineStatus' : IDL.Func([IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };