/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface GroupChat {
    id: string;
    members: Array<UserId>;
    name: string;
    createdAt: Timestamp;
    lastMessage?: string;
    lastUpdated: Timestamp;
    typing: Array<[string, boolean]>;
    description: string;
    adminId: UserId;
}
export interface Chat {
    muted: Array<[string, boolean]>;
    participants: Array<UserId>;
    vanishMode: boolean;
    createdAt: Timestamp;
    lastMessage?: MessageId;
    lastUpdated: Timestamp;
    typing: Array<[string, boolean]>;
    pinned: Array<[string, boolean]>;
    archived: Array<[string, boolean]>;
}
export type MessageId = string;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Message {
    edited: boolean;
    createdAt: Timestamp;
    text: string;
    vanish: boolean;
    seenBy: Array<UserId>;
    mediaUrl: string;
    messageType: MessageType;
    deletedForEveryone: boolean;
    replyTo?: MessageId;
    editedAt?: Timestamp;
    reactions: Array<[string, Array<UserId>]>;
    senderId: UserId;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    _id: UserId;
    bio: string;
    blockedUsers: Array<UserId>;
    timezone: string;
    fcmToken: string;
    username: string;
    birthDate: string;
    websiteUrl: string;
    createdAt: Timestamp;
    fullName: string;
    email: string;
    isPrivate: boolean;
    onlineStatus: boolean;
    phoneNumber: string;
    followers: Array<UserId>;
    following: Array<UserId>;
    profilePicture: string;
    lastSeen: Timestamp;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum MessageType {
    gif = "gif",
    video = "video",
    voice = "voice",
    file = "file",
    text = "text",
    image = "image"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addGroupMember(groupId: string, userId: Principal): Promise<void>;
    addReaction(chatId: string, messageId: string, emoji: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockUser(targetId: Principal): Promise<void>;
    createGroupChat(name: string, description: string, memberIds: Array<Principal>): Promise<string>;
    createOrUpdateUserProfile(profile: UserProfile): Promise<void>;
    createTemporaryFolder(folderName: string): Promise<void>;
    deleteAccount(): Promise<void>;
    deleteMessageForEveryone(chatId: string, messageId: string): Promise<void>;
    deleteTemporaryFolder(folderName: string): Promise<void>;
    editMessage(chatId: string, messageId: string, newText: string): Promise<void>;
    followUser(targetId: Principal): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatById(chatId: string): Promise<Chat | null>;
    getChatMessages(chatId: string, afterTimestamp: bigint): Promise<Array<Message>>;
    getEmailByPhoneNumber(_phoneNumber: string): Promise<string>;
    getGroupById(groupId: string): Promise<GroupChat | null>;
    getGroupMessages(groupId: string, afterTimestamp: bigint): Promise<Array<Message>>;
    getLifestyleChoices(): Promise<Array<string>>;
    getMyChats(): Promise<Array<Chat>>;
    getMyGroupChats(): Promise<Array<GroupChat>>;
    getOrCreateChat(otherUser: Principal): Promise<Chat>;
    getPersonalityTypes(): Promise<Array<string>>;
    getRelationshipStatuses(): Promise<Array<string>>;
    getTemporaryFolders(): Promise<Array<string>>;
    getTypingStatus(chatId: string): Promise<Array<[string, boolean]>>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    getWellBeingPractices(): Promise<Array<string>>;
    isCallerAdmin(): Promise<boolean>;
    leaveGroup(groupId: string): Promise<void>;
    markGroupMessagesSeen(groupId: string): Promise<void>;
    markMessagesSeen(chatId: string): Promise<void>;
    removeGroupMember(groupId: string, userId: Principal): Promise<void>;
    removeReaction(chatId: string, messageId: string, emoji: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchFolders(searchText: string): Promise<Array<string>>;
    searchProfiles(searchText: string): Promise<Array<UserProfile>>;
    searchUsersByUsername(searchText: string): Promise<Array<UserProfile>>;
    searchUsersByUsernamePrefix(prefix: string): Promise<Array<UserProfile>>;
    sendGroupMessage(groupId: string, text: string, messageType: string, mediaUrl: string, replyTo: string): Promise<Message>;
    sendMessage(chatId: string, text: string, messageType: string, mediaUrl: string, replyTo: string): Promise<Message>;
    setGroupTypingStatus(groupId: string, isTyping: boolean): Promise<void>;
    setTypingStatus(chatId: string, isTyping: boolean): Promise<void>;
    toggleArchive(chatId: string): Promise<void>;
    toggleMute(chatId: string): Promise<void>;
    togglePin(chatId: string): Promise<void>;
    toggleVanishMode(chatId: string): Promise<void>;
    unblockUser(targetId: Principal): Promise<void>;
    unfollowUser(targetId: Principal): Promise<void>;
    updateGroupInfo(groupId: string, name: string, description: string): Promise<void>;
    updateLastSeen(): Promise<void>;
    updateOnlineStatus(status: boolean): Promise<void>;
}
import type { Chat as _Chat, GroupChat as _GroupChat, Message as _Message, MessageId as _MessageId, MessageType as _MessageType, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addGroupMember(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroupMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroupMember(arg0, arg1);
            return result;
        }
    }
    async addReaction(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async createGroupChat(arg0: string, arg1: string, arg2: Array<Principal>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroupChat(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroupChat(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrUpdateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateUserProfile(arg0);
            return result;
        }
    }
    async createTemporaryFolder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTemporaryFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTemporaryFolder(arg0);
            return result;
        }
    }
    async deleteAccount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccount();
            return result;
        }
    }
    async deleteMessageForEveryone(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessageForEveryone(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessageForEveryone(arg0, arg1);
            return result;
        }
    }
    async deleteTemporaryFolder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTemporaryFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTemporaryFolder(arg0);
            return result;
        }
    }
    async editMessage(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatById(arg0: string): Promise<Chat | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatById(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatById(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatMessages(arg0: string, arg1: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0, arg1);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0, arg1);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmailByPhoneNumber(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmailByPhoneNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmailByPhoneNumber(arg0);
            return result;
        }
    }
    async getGroupById(arg0: string): Promise<GroupChat | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupById(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupById(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupMessages(arg0: string, arg1: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupMessages(arg0, arg1);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupMessages(arg0, arg1);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLifestyleChoices(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLifestyleChoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLifestyleChoices();
            return result;
        }
    }
    async getMyChats(): Promise<Array<Chat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyChats();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyChats();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyGroupChats(): Promise<Array<GroupChat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyGroupChats();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyGroupChats();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrCreateChat(arg0: Principal): Promise<Chat> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateChat(arg0);
                return from_candid_Chat_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateChat(arg0);
            return from_candid_Chat_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPersonalityTypes(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalityTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalityTypes();
            return result;
        }
    }
    async getRelationshipStatuses(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelationshipStatuses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelationshipStatuses();
            return result;
        }
    }
    async getTemporaryFolders(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemporaryFolders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemporaryFolders();
            return result;
        }
    }
    async getTypingStatus(arg0: string): Promise<Array<[string, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTypingStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTypingStatus(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWellBeingPractices(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWellBeingPractices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWellBeingPractices();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async leaveGroup(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveGroup(arg0);
            return result;
        }
    }
    async markGroupMessagesSeen(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markGroupMessagesSeen(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markGroupMessagesSeen(arg0);
            return result;
        }
    }
    async markMessagesSeen(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessagesSeen(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessagesSeen(arg0);
            return result;
        }
    }
    async removeGroupMember(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeGroupMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeGroupMember(arg0, arg1);
            return result;
        }
    }
    async removeReaction(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReaction(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchFolders(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFolders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFolders(arg0);
            return result;
        }
    }
    async searchProfiles(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProfiles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProfiles(arg0);
            return result;
        }
    }
    async searchUsersByUsername(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsersByUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsersByUsername(arg0);
            return result;
        }
    }
    async searchUsersByUsernamePrefix(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsersByUsernamePrefix(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsersByUsernamePrefix(arg0);
            return result;
        }
    }
    async sendGroupMessage(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendGroupMessage(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Message_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendGroupMessage(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Message_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Message_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Message_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async setGroupTypingStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGroupTypingStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGroupTypingStatus(arg0, arg1);
            return result;
        }
    }
    async setTypingStatus(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTypingStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTypingStatus(arg0, arg1);
            return result;
        }
    }
    async toggleArchive(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleArchive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleArchive(arg0);
            return result;
        }
    }
    async toggleMute(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleMute(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleMute(arg0);
            return result;
        }
    }
    async togglePin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePin(arg0);
            return result;
        }
    }
    async toggleVanishMode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleVanishMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleVanishMode(arg0);
            return result;
        }
    }
    async unblockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async updateGroupInfo(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGroupInfo(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGroupInfo(arg0, arg1, arg2);
            return result;
        }
    }
    async updateLastSeen(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLastSeen();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLastSeen();
            return result;
        }
    }
    async updateOnlineStatus(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOnlineStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOnlineStatus(arg0);
            return result;
        }
    }
}
function from_candid_Chat_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Chat): Chat {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_GroupChat_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroupChat): GroupChat {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MessageType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageType): MessageType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Chat]): Chat | null {
    return value.length === 0 ? null : from_candid_Chat_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MessageId]): MessageId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GroupChat]): GroupChat | null {
    return value.length === 0 ? null : from_candid_GroupChat_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    muted: Array<[string, boolean]>;
    participants: Array<_UserId>;
    vanishMode: boolean;
    createdAt: _Timestamp;
    lastMessage: [] | [_MessageId];
    lastUpdated: _Timestamp;
    typing: Array<[string, boolean]>;
    pinned: Array<[string, boolean]>;
    archived: Array<[string, boolean]>;
}): {
    muted: Array<[string, boolean]>;
    participants: Array<UserId>;
    vanishMode: boolean;
    createdAt: Timestamp;
    lastMessage?: MessageId;
    lastUpdated: Timestamp;
    typing: Array<[string, boolean]>;
    pinned: Array<[string, boolean]>;
    archived: Array<[string, boolean]>;
} {
    return {
        muted: value.muted,
        participants: value.participants,
        vanishMode: value.vanishMode,
        createdAt: value.createdAt,
        lastMessage: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.lastMessage)),
        lastUpdated: value.lastUpdated,
        typing: value.typing,
        pinned: value.pinned,
        archived: value.archived
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    edited: boolean;
    createdAt: _Timestamp;
    text: string;
    vanish: boolean;
    seenBy: Array<_UserId>;
    mediaUrl: string;
    messageType: _MessageType;
    deletedForEveryone: boolean;
    replyTo: [] | [_MessageId];
    editedAt: [] | [_Timestamp];
    reactions: Array<[string, Array<_UserId>]>;
    senderId: _UserId;
}): {
    edited: boolean;
    createdAt: Timestamp;
    text: string;
    vanish: boolean;
    seenBy: Array<UserId>;
    mediaUrl: string;
    messageType: MessageType;
    deletedForEveryone: boolean;
    replyTo?: MessageId;
    editedAt?: Timestamp;
    reactions: Array<[string, Array<UserId>]>;
    senderId: UserId;
} {
    return {
        edited: value.edited,
        createdAt: value.createdAt,
        text: value.text,
        vanish: value.vanish,
        seenBy: value.seenBy,
        mediaUrl: value.mediaUrl,
        messageType: from_candid_MessageType_n20(_uploadFile, _downloadFile, value.messageType),
        deletedForEveryone: value.deletedForEveryone,
        replyTo: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.replyTo)),
        editedAt: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.editedAt)),
        reactions: value.reactions,
        senderId: value.senderId
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    members: Array<_UserId>;
    name: string;
    createdAt: _Timestamp;
    lastMessage: [] | [string];
    lastUpdated: _Timestamp;
    typing: Array<[string, boolean]>;
    description: string;
    adminId: _UserId;
}): {
    id: string;
    members: Array<UserId>;
    name: string;
    createdAt: Timestamp;
    lastMessage?: string;
    lastUpdated: Timestamp;
    typing: Array<[string, boolean]>;
    description: string;
    adminId: UserId;
} {
    return {
        id: value.id,
        members: value.members,
        name: value.name,
        createdAt: value.createdAt,
        lastMessage: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.lastMessage)),
        lastUpdated: value.lastUpdated,
        typing: value.typing,
        description: value.description,
        adminId: value.adminId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gif: null;
} | {
    video: null;
} | {
    voice: null;
} | {
    file: null;
} | {
    text: null;
} | {
    image: null;
}): MessageType {
    return "gif" in value ? MessageType.gif : "video" in value ? MessageType.video : "voice" in value ? MessageType.voice : "file" in value ? MessageType.file : "text" in value ? MessageType.text : "image" in value ? MessageType.image : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Chat>): Array<Chat> {
    return value.map((x)=>from_candid_Chat_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GroupChat>): Array<GroupChat> {
    return value.map((x)=>from_candid_GroupChat_n24(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
